### PR TITLE
Solution Added

### PR DESCRIPTION
**Pull request by night-thinker-abhi**

### CODE REVIEW

**Comment by night-thinker-abhi** [comment]
Please Review.

**Review by 100sarthak100 — CHANGES_REQUESTED** [review]
Thank you for your collaboration. The solution is right but you have to make some changes.
- Add the Question description.
- Input & Output Samples
- Time and Space Complexity

You can take this solution as a reference ->
https://github.com/100sarthak100/DataStructures-Algorithms/blob/master/Code/LeetcodePattern/Arrays/leadersInanArray.cpp

Make sure you comment out these details.

**Comment by night-thinker-abhi** [comment]
The requested changes have been done please review.

**Review by 100sarthak100 — APPROVED** [review]
Your PR is approved. Thank you for your contribution.

**Pull request merged**
